[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_token_program = "43uxjSHdLq7ahspsXwkCBLBh3qmgLf6A38RBbJgHycfK"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/arlen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
